In [1]:
# imports
import sys
import numpy as np
import pandas as pd
sys.path.append('../../') # to access the files in higher directories
sys.path.append('../') # to access the files in higher directories
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

import core_exp as cx
import core_calib as cal
import core_tools as ct

In [2]:
data_list = [
                "vertebral", 
                "wilt",
                "parkinsons", 
                "heart",
                "wdbc",
                "bank", 
                "ionosphere", 
                "HRCompetencyScores",
                "spambase", 
                "QSAR", 
                "diabetes", 
                "breast", 
                "SPF",
                "hillvalley",
                "pc4",
                "scene",
                "Sonar_Mine_Rock_Data",
                "Customer_Churn",
                "jm1",
                "eeg",
            ]

In [3]:
data_info = ct.real_data_info(data_list)
data_info_sorted = data_info.sort_values(by='instances').reset_index()
data_info_sorted.drop(columns=["index"], inplace=True)
data_info_sorted.index = data_info_sorted.index + 1
data_info_sorted["major class"] = data_info_sorted["major class"].round(1)
data_info_sorted.to_latex(f"data_info.txt")
data_info_sorted

/var/folders/gm/nlbfzh25075c0jwn9khghrfw0000gn/T/ipykernel_23794/1034276766.py:6: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  data_info_sorted.to_latex(f"data_info.txt")

                    Name  instances  features  major class
1             parkinsons        195        22         75.4
2   Sonar_Mine_Rock_Data        208        60         53.4
3     HRCompetencyScores        300         9         53.0
4                  heart        303        13         54.5
5              vertebral        310         6         67.7
6             ionosphere        351        34         64.1
7                   wdbc        569        30         62.7
8                 breast        569        30         62.7
9               diabetes        768         8         65.1
10                  QSAR       1055        41         66.3
11            hillvalley       1212       100         50.0
12                  bank       1372         4         55.5
13                   pc4       1458        37         87.8
14                   SPF       1941        33         65.3
15                 scene       2407       299         82.1
16        Customer_Churn       3150        13         84.3
17              spambase       4601        57         60.6
18                  wilt       4839         5         94.6
19                   jm1      10880        21         80.7
20                   eeg      14980        14         55.1