In [1]:
# imports
import sys
import numpy as np
import pandas as pd
sys.path.append('../../') # to access the files in higher directories
sys.path.append('../') # to access the files in higher directories
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

import core_exp as cx
import core_calib as cal
import core_tools as ct

In [2]:
data_list = [
                  "cm1",
                  "datatrieve",
                  "kc1_class_level_defectiveornot",
                  "kc1",
                  "kc2",
                  "kc3",
                  "pc1",
                  "spect",
                  "spectf",
                  "vertebral", 
                  "wilt",
                  "parkinsons", 
                  "heart",
                  "wdbc",
                  "bank", 
                  "ionosphere", 
                  "HRCompetencyScores",
                  "spambase", 
                  "QSAR", 
                  "diabetes", 
                  "breast", 
                  "SPF",
                  "hillvalley",
                  "pc4",
                  "scene",
                  "Sonar_Mine_Rock_Data",
                  "Customer_Churn",
                  "jm1",
                  "eeg",
                  "phoneme",
            ]

In [3]:
data_info = ct.real_data_info(data_list)
data_info_sorted = data_info.sort_values(by='instances').reset_index()
data_info_sorted.drop(columns=["index"], inplace=True)
data_info_sorted.index = data_info_sorted.index + 1
data_info_sorted["major class"] = data_info_sorted["major class"].round(1)
data_info_sorted.to_latex(f"data_info.txt")
data_info_sorted

/var/folders/gm/nlbfzh25075c0jwn9khghrfw0000gn/T/ipykernel_28532/1034276766.py:6: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  data_info_sorted.to_latex(f"data_info.txt")

                              Name  instances  features  major class
1                       datatrieve        130         8         91.5
2   kc1_class_level_defectiveornot        145        94         58.6
3                       parkinsons        195        22         75.4
4             Sonar_Mine_Rock_Data        208        60         53.4
5                            spect        267        22         79.4
6                           spectf        267        44         79.4
7               HRCompetencyScores        300         9         53.0
8                            heart        303        13         54.5
9                        vertebral        310         6         67.7
10                      ionosphere        351        34         64.1
11                             kc3        458        39         90.6
12                             cm1        498        21         90.2
13                             kc2        522        21         79.5
14                            wdbc        569        30         62.7
15                          breast        569        30         62.7
16                        diabetes        768         8         65.1
17                            QSAR       1055        41         66.3
18                             pc1       1109        21         93.1
19                      hillvalley       1212       100         50.0
20                            bank       1372         4         55.5
21                             pc4       1458        37         87.8
22                             SPF       1941        33         65.3
23                             kc1       2109        21         84.5
24                           scene       2407       299         82.1
25                  Customer_Churn       3150        13         84.3
26                        spambase       4601        57         60.6
27                            wilt       4839         5         94.6
28                         phoneme       5404         5         70.7
29                             jm1      10880        21         80.7
30                             eeg      14980        14         55.1